### ISSUE TITLE
Functional vs. Container components

### ISSUE THREAD

**Issue by SamCatherman** [learn-co-curriculum/react-async-fetch-lab#1]
The README asks 'App.js' to be written as a functional component, and the next line asks it to include a 'componentDidMount()' method call with a fetch inside. In the solution branch, 'App.js' is a container component, and the call to fetch returns its data to App's state. A student came to me very confused about this today, unsure about where to write 'componentDidMount' inside of a functional component. Some research revealed that one way to do this would be through 'https://www.npmjs.com/package/react-pure-lifecycle,' but the README preceding this lab makes no mention of it. 

Additionally, the "Button", "Example", and "Greeting" components aren't used anywhere else in the App.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
